import Head from "next/head";
import Image from "next/image";
import { Fragment } from "react";
import HomePage from "../../components/home-page/home-page";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>KIM MAN KHI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </Fragment>
  );
}
